### ISSUE TITLE
1.11.4 : erreur de parsing des pdf 

### ISSUE THREAD

**Issue by hjacob35** [EsupPortail/esup-signature#21]
Bonjour, sur la v1.11.4, j'ai une erreur lors du dépôt manuel ou cmis de fichiers pdf :

**Comment by hjacob35** [comment]
`
2021-04-21 19:18:57.923  INFO 9156 --- [task-scheduler-4] o.e.e.s.i.fs.opencmis.CmisAccessImpl     : get file list from : /default-domain/workspaces/esup-signature/Formation/ConventionsStage/en-preparation
2021-04-21 19:18:58.025  INFO 9156 --- [task-scheduler-4] o.e.e.service.WorkflowService            : adding file : Installation Gemalto.pdf
2021-04-21 19:18:58.174 ERROR 9156 --- [task-scheduler-4] o.e.e.service.utils.pdf.PdfService       : error on search metadatas

org.apache.xmpbox.xml.XmpParsingException: Failed to parse
	at org.apache.xmpbox.xml.DomXmpParser.parse(DomXmpParser.java:126)
	at org.esupportail.esupsignature.service.utils.pdf.PdfService.readMetadatas(PdfService.java:220)
	at org.esupportail.esupsignature.service.WorkflowService.importFilesFromSource(WorkflowService.java:266)
	at org.esupportail.esupsignature.service.WorkflowService$$FastClassBySpringCGLIB$$7af7080.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.esupportail.esupsignature.service.WorkflowService$$EnhancerBySpringCGLIB$$7e2d13bb.importFilesFromSource(<generated>)
	at org.esupportail.esupsignature.service.scheduler.ScheduledTaskService.scanAllSignbooksSources(ScheduledTaskService.java:65)
	at org.esupportail.esupsignature.service.scheduler.ScheduledTaskService$$FastClassBySpringCGLIB$$386f660c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.esupportail.esupsignature.service.scheduler.ScheduledTaskService$$EnhancerBySpringCGLIB$$929ccbdf.scanAllSignbooksSources(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor491.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at org.apache.xmpbox.xml.DomXmpParser.parse(DomXmpParser.java:122)
	... 38 common frames omitted

2021-04-21 19:18:58.281  INFO 9156 --- [task-scheduler-4] o.e.e.service.SignBookService            : import workflow steps in signBook Installation Gemalto.pdf_0 - 527
2021-04-21 19:18:58.501  INFO 9156 --- [task-scheduler-4] o.e.e.service.SignBookService            : Circuit 527 envoyé pour signature de l'étape 1

`

**Comment by dlemaignent** [comment]
Bonjour,
Une correction concernant la partie cmis a été poussée dans la version 1.12.1. Pour l'erreur concernant les metadatas, le niveau de log est passé en warn sans la trace car ce problème se produit dès qu'il n'y a pas de métadonnées dans le document.
Merci d'avance pour le retour.
